name: CI-develop

on:
  push:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
        
      - name: Get cache
        uses: actions/cache@v2
        with:
          path: |
              packages
              TbsCore/obj/project.assets.json
              TbsCore/TbsCore.csproj.nuget.g.targets
              TbsCore/TbsCore.csproj.nuget.g.props.              
          key: ${{ runner.os }}-nuget3-${{ hashFiles('TbsCore/packages.lock.json') }}
          restore-keys: |
              ${{ runner.os }}-nuget3-
              
      - name: Restore Packages
        run: |
          nuget restore TbsCore/TbsCore.csproj -PackagesDirectory packages
          nuget restore TravBotSharp/TbsWinForms.csproj -PackagesDirectory packages
        
      - name: Build Bot
        run: |
          msbuild.exe TravBotSharp.sln /t:TbsWinForms /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /m /p:BuildProjectReferences=true
          
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: TBS-pre
          path: TravBotSharp\bin\Release
          
  Pre-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        
      - name: 'Get next version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
        
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: TBS-pre
          path: TravBotSharp/bin/Release
      
      - name: Archive pre release
        uses: papeloto/action-zip@v1
        with:
            files: TravBotSharp/bin/Release
            dest: TBS-${{ steps.semvers.outputs.patch }}.zip
      
      - name: Create pre release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.semvers.outputs.patch }}
          prerelease: true
          title: TBS-${{ steps.semvers.outputs.patch }}-pre
          files: TBS-${{ steps.semvers.outputs.patch }}.zip
          
      - name: Create pre release
        uses: ncipollo/release-action@v1
        with:
          name: TBS-${{ steps.semvers.outputs.patch }}-pre
          prerelease: true
          tag: ${{ steps.semvers.outputs.patch }}
          commit: develop
          body: "Changelog: ${{ github.event.head_commit.message }}"
          artifacts: TBS-${{ steps.semvers.outputs.patch }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          
  Clear:
    runs-on: ubuntu-latest
    needs: Pre-release
    steps:
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: TBS-pre
